=== Vladanak/Java/jLab5/files/airlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/airlist"
        xmlns:tns="http://www.example.com/airlist"
        elementFormDefault="qualified">
    <element name="airlist">
        <complexType>
            <sequence>
                <element name="air" type="tns:Air" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Air">
        <sequence>
            <element name="loadCapacity" type="positiveInteger" />
            <element name="countPassengers" type="positiveInteger" />
            <element name="range" type="positiveInteger" />
            <element name="speed" type="positiveInteger" />
        </sequence>
        <attribute name="airType" default="Boeing707">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Boeing707"/>
                    <enumeration value="IL76"/>
                    <enumeration value="A320"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
</schema>

=== Vladanak/Java/jLab5/files/airlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="air.xsl"?>
<airlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/airlist"
         xsi:schemaLocation="http://www.example.com/airlist airlist.xsd">
    <air airType="Boeing707">
        <loadCapacity>1000</loadCapacity>
        <countPassengers>60</countPassengers>
        <range>5150</range>
        <speed>888</speed>
    </air>
    <air airType="IL76">
        <loadCapacity>600</loadCapacity>
        <countPassengers>20</countPassengers>
        <range>4679</range>
        <speed>690</speed>
    </air>
    <air airType="A320">
        <loadCapacity>800</loadCapacity>
        <countPassengers>70</countPassengers>
        <range>4100</range>
        <speed>768</speed>
    </air>
</airlist>
